name: Automatic Deployment to BETA Update Site
on:
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string

jobs:
  build:
    name: Build & Deploy
    if: ${{ vars.CURRENT_BETA_BRANCH == inputs.source-branch }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Checkout Update Site Repository
        uses: actions/checkout@v4
        with:
          repository: DevEpos/eclipse.devepos.com
          path: site

      - name: Checkout Plugins/features
        uses: actions/checkout@v4
        with:
          repository: DevEpos/eclipse-adt-plugins
          ref: ${{ inputs.source-branch }}
          path: plugin-build

      - name: Remove cached DevEpos artifacts
        shell: pwsh
        run: |
          .\site\scripts\Remove-DeveposM2.ps1

      - name: Build plugins/features
        run: |
          cd ./plugin-build
          mvn -B install -DskipTests

      - name: Build update site
        run: |
          cd ./site/beta
          mvn -B clean install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          cd ./site
          git add beta
          git commit -m "chore(ci): automatic deployment to beta site" || echo "No changes to commit"

      - name: Deploy changes
        run: |
          cd ./site
          git push
