name: Build Prod Updatesite

on:
  workflow_dispatch:
    inputs:
      skipGitChangeCheck:
        description: Skips git change check
        required: false
        default: false
        type: boolean

env:
  SKIP_GIT_CHANGE_CHECK: ${{github.event.inputs.skipGitChangeCheck}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Checkout Plugins/features
        uses: actions/checkout@v4
        with:
          repository: DevEpos/eclipse-adt-plugins
          path: plugin-build

      - name: Set production versions
        shell: pwsh
        run: |
          .\scripts\Set-Versions.ps1 -RepoBasePath .\plugin-build -RepoListPath .\scripts\repos.txt

      - name: Remove cached DevEpos artifacts
        shell: pwsh
        run: |
          .\scripts\Remove-DeveposM2.ps1

      - name: Build plugins/features
        run: |
          cd ./plugin-build
          mvn -B install -DskipTests

      - name: Build update site
        run: |
          cd ./latest
          mvn -B clean install

      - name: Check for added or renamed files
        id: file_check
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch
          git add latest
          CHANGES=$(git status --porcelain latest | grep -E '^\s*(A|R)' || true)
          if [ -n "$CHANGES" ] || [ "$SKIP_GIT_CHANGE_CHECK" == "true" ]; then
            echo "New files detected > PR will be created"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: steps.file_check.outputs.changed == 'true'        
        with:
          commit-message: "chore: build prod update site"
          branch: "release/latest"
          title: "Prod Update site Build"
          delete-branch: true
          add-paths: "latest/**"
