name: Build Dev Updatesite

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Checkout Plugins/features
        uses: actions/checkout@v4
        with:
          repository: DevEpos/eclipse-adt-plugins
          path: feat_plugins

      - name: Build plugins/features
        run: |
          cd ./feat_plugins
          mvn -B install -DskipTests

      - name: Build update site
        run: |
          cd ./dev
          mvn -B install
          ls ./target/updatesite*

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: build dev update site"
          branch: "build-dev-update-site"
          title: "Dev Update site Build"
          add-paths: dev/**
