name: Build Prod Updatesite

on:
  workflow_dispatch:
env:
  SKIP_GIT_CHANGE_CHECK: ${{ vars.SKIP_GIT_CHANGE_CHECK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check variable state
        run: |
          echo "Varible SKIP_GIT_CHANGE_CHECK: $SKIP_GIT_CHANGE_CHECK"

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Checkout Plugins/features
        uses: actions/checkout@v4
        with:
          repository: DevEpos/eclipse-adt-plugins
          path: feat_plugins

      - name: Set production versions
        shell: pwsh
        run: |
          .\scripts\Set-Versions.ps1 -RepoBasePath .\feat_plugins -RepoListPath .\scripts\repos.txt

      - name: Remove cached DevEpos artifacts
        shell: pwsh
        run: |
          .\scripts\Remove-DeveposM2.ps1

      - name: Build plugins/features
        run: |
          cd ./feat_plugins
          mvn -B install -DskipTests

      - name: Build update site
        run: |
          cd ./latest
          mvn -B install

      - name: Check for added or renamed files
        id: file_check
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch
          git add latest
          CHANGES=$(git status --porcelain latest | grep -E '^\s*(A|R)' || true)
          if [ -n "$CHANGES" ] || [ "$SKIP_GIT_CHANGE_CHECK" == "true" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

#      - name: Create commit
#        if: steps.file_check.outputs.changed == 'true'
#        run: |
#          git config user.name 'github-actions[bot]'
#          git config user.email 'github-actions[bot]@users.noreply.github.com'
#          git add -A
#          git commit -m "chore: build prod update site"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: steps.file_check.outputs.changed == 'true'        
        with:
          branch: "build-prod-update-site"
          title: "Prod Update site Build"
          delete-branch: true
          add-paths: "latest/**"
